### ISSUE TITLE
Facing issue with '<img src={{thumb('/image/bg.png', 100, 100)}}/>' 

### ISSUE THREAD

**Issue by PrinceShakya** [tinkeshwar/laravel-image#2]
I have used your library every think is good but i'm facing issue with static image. trying to create thumb using your tag '<img src={{thumb('/image/bg.png', 100, 100)}}/>'  is not working as expected.

**Comment by tinkeshwar** [comment]
On it.

**Comment by tinkeshwar** [comment]
Resolved in v2.1.2
